spring:
  datasource:
    url: jdbc:sqlserver://${SQL_SERVER_URL:localhost}:1433;
      databaseName=ThrumiApplication;
      encrypt=false;
      trustServerCertificate=true;
      loginTimeout=30;
      socketTimeout=60
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 120000
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        max-interval: 10000
        multiplier: 1.5
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
        jdbc:
          time_zone: UTC
        connection:
          provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
        hbm2ddl:
          auto: validate
        format_sql: true
        
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${POD_NAME:${spring.application.name}}
    metadata-map:
      k8s-namespace: ${NAMESPACE:default}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
