spring:
  datasource:
    url: jdbc:sqlserver://${SQL_SERVER_URL:localhost}:1433;databaseName=ThrumiApplication;encrypt=false;trustServerCertificate=true
    username: ${USERNAME}
    password: ${PASSWORD}
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
