spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**

resilience4j:
  circuitbreaker:
    instances:
      USER-SERVICE:
        baseConfig: default
      DEPARTMENT-SERVICE:
        baseConfig: default

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${POD_NAME:${spring.application.name}}
    metadata-map:
      k8s-namespace: ${NAMESPACE:default}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
