spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**

resilience4j:
  circuitbreaker:
    instances:
      USER-SERVICE:
        baseConfig: default
      DEPARTMENT-SERVICE:
        baseConfig: default
